#
# Makefile for the Profile lab
# 
CC = gcc

IFLAGS  = -I/comp/40/build/include -I/usr/sup/cii40/include/cii
CFLAGS  = -g -std=gnu99 -Wall -Wextra -Werror -pedantic $(IFLAGS)
LDFLAGS = -g -L/comp/40/build/lib -L/usr/sup/cii40/lib64
LDLIBS  = -lpnmrdr -lcii40-O2 -lm

EXECS   = unblackedges unblackedges-bfs

all: $(EXECS) 

unblackedges: unblackmain.o pbmio.o unblackedges-lab.o bit2.o
	$(CC) $(LDFLAGS) $^ -o $@ $(LDLIBS)

unblackedges-bfs: unblackmain.o pbmio.o unblackedges-queue.o bit2.o
	$(CC) $(LDFLAGS) $^ -o $@ $(LDLIBS)

# To get *any* .o file, compile its .c file with the following rule.
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(EXECS)  *.o

